all: compile link

CXXFLAGS = -INeural_Network/FFNN -INeural_Network/Classifier -INeural_Network/Dataset -INeural_Network/Blocks -INeural_Network/Utilities -Ilibs/include

SOURCES = $(wildcard Neural_Network/*.cpp) \
          $(wildcard Neural_Network/Classifier/*.cpp) \
          $(wildcard Neural_Network/FFNN/*.cpp) \
          $(wildcard Neural_Network/Blocks/*.cpp) \
          $(wildcard Neural_Network/Dataset/*.cpp) \
          $(wildcard Neural_Network/Utilities/*.cpp)

compile:
	g++ $(CXXFLAGS) -c $(SOURCES)

link:
	g++ *.o -o main -Llibs/lib -lsfml-graphics -lsfml-window -lsfml-system